from __future__ import annotations


ALFHEIM_POSSESSION_ARGUMENTS = (
    "--no-shots",
    "--control-radius-heights",
    "1.8",
    "--identity-switch-radius-heights",
    "0.75",
    "--co-visible-track-return-seconds",
    "0.21",
    "--smoothing-seconds",
    "1.0",
    "--minimum-transfer-heights",
    "0.5",
    "--minimum-pass-speed",
    "45",
    "--pass-debounce-seconds",
    "1.2",
    "--pass-sender-lookback-seconds",
    "6",
    "--pass-receiver-window-seconds",
    "3",
    "--maximum-flyby-speed",
    "500",
    "--maximum-ground-contact-height-ratio",
    "0.4",
    "--maximum-aerial-contact-direction-cosine",
    "0.5",
    "--minimum-flyby-direction-cosine",
    "0.95",
    "--occluded-owner-max-seconds",
    "4",
    "--occluded-owner-max-speed-heights-per-second",
    "3",
    "--occluded-owner-min-direction-cosine",
    "0",
    "--boundary-ownership-lookback-seconds",
    "6",
)
