"""Coordination persistence for distributed football review workflows."""

from football_poc.coordination.config import CoordinationConfig
from football_poc.coordination.identity import (
    IdentityError,
    MachineIdentity,
    load_or_create_machine_identity,
)
from football_poc.coordination.memory import InMemoryCoordinationRepository
from football_poc.coordination.migrations import MigrationResult
from football_poc.coordination.models import (
    Artifact,
    AuditEntry,
    ClaimedJob,
    DatabaseHealth,
    DatabaseMode,
    EditingLease,
    EnvironmentIdentity,
    Identity,
    JobTerminalResult,
    HistoricalImportOutcome,
    HistoricalImportSource,
    ManualEventMapping,
    ManualEventRevision,
    ManualReferenceMember,
    ManualReferenceSetRevision,
    Segment,
    StateSnapshot,
)
from football_poc.coordination.postgres import (
    BootstrapResult,
    ReconciliationHook,
    ReconciliationResult,
    bootstrap_coordination,
    create_coordination_repository,
    run_coordination_preflight,
)
from football_poc.coordination.repository import (
    AuthorityRetiredError,
    CoordinationError,
    CoordinationRepository,
    DatabaseUnavailableError,
    LEASE_EXPIRY_SECONDS,
    LEASE_HEARTBEAT_SECONDS,
    LeaseConflictError,
    LeaseTokenError,
    ManualReferenceConflictError,
    StateVersionConflictError,
)

__all__ = [
    "Artifact",
    "AuditEntry",
    "BootstrapResult",
    "AuthorityRetiredError",
    "ClaimedJob",
    "CoordinationConfig",
    "CoordinationError",
    "CoordinationRepository",
    "DatabaseHealth",
    "DatabaseMode",
    "DatabaseUnavailableError",
    "EditingLease",
    "EnvironmentIdentity",
    "Identity",
    "IdentityError",
    "JobTerminalResult",
    "HistoricalImportOutcome",
    "HistoricalImportSource",
    "ManualEventMapping",
    "ManualEventRevision",
    "ManualReferenceConflictError",
    "ManualReferenceMember",
    "ManualReferenceSetRevision",
    "InMemoryCoordinationRepository",
    "LeaseConflictError",
    "LEASE_EXPIRY_SECONDS",
    "LEASE_HEARTBEAT_SECONDS",
    "LeaseTokenError",
    "MachineIdentity",
    "MigrationResult",
    "ReconciliationHook",
    "ReconciliationResult",
    "Segment",
    "StateSnapshot",
    "StateVersionConflictError",
    "create_coordination_repository",
    "bootstrap_coordination",
    "load_or_create_machine_identity",
    "run_coordination_preflight",
]
