"""Generate tests/RULE_INDEX.md from timestamped rule unit tests.

Every test in tests/rules and tests/tracking is named
``test_<rule>_YYYYMMDDTHHMMSSmmmZ``. The index lists them chronologically so a
failing test identifies the rule and when it was implemented.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RULE_DIRECTORIES = ("tests/rules", "tests/tracking")
INDEX_PATH = PROJECT_ROOT / "tests" / "RULE_INDEX.md"
TIMESTAMP = re.compile(r"^test_(?P<rule>.+)_(?P<stamp>\d{8}T\d{9}Z)$")


def collect_rule_tests() -> tuple[list[dict], list[str]]:
    rules: list[dict] = []
    unstamped: list[str] = []
    for directory in RULE_DIRECTORIES:
        for path in sorted((PROJECT_ROOT / directory).glob("test_*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            for node in tree.body:
                if not (
                    isinstance(node, ast.FunctionDef)
                    and node.name.startswith("test_")
                ):
                    continue
                relative = path.relative_to(PROJECT_ROOT).as_posix()
                match = TIMESTAMP.match(node.name)
                if not match:
                    unstamped.append(f"{relative}::{node.name}")
                    continue
                doc = (ast.get_docstring(node) or "").strip().splitlines()
                rules.append({
                    "stamp": match["stamp"],
                    "rule": match["rule"].replace("_", " "),
                    "area": directory.split("/")[-1],
                    "test": f"{relative}::{node.name}",
                    "description": doc[0] if doc else "",
                })
    rules.sort(key=lambda item: (item["stamp"], item["test"]))
    return rules, unstamped


def render_index(rules: list[dict]) -> str:
    lines = [
        "# Rule unit-test index",
        "",
        "Generated by `python scripts/generate-rule-index.py`. Do not edit.",
        "",
        "Each implemented rule or fix has one timestamped unit test. A failing",
        "test names the rule that broke. Older behaviour is also covered by the",
        "baseline suites (`tests/test_possession.py`, `tests/test_match_state.py`,",
        "`tests/test_player_tracking.py`, `tests/test_shots_on_target.py`,",
        "`tests/test_shot_evidence.py`).",
        "",
        "| Implemented (UTC) | Area | Rule | Test |",
        "| --- | --- | --- | --- |",
    ]
    for item in rules:
        rule = item["description"] or item["rule"]
        lines.append(
            f"| {item['stamp']} | {item['area']} | {rule} | `{item['test']}` |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    rules, unstamped = collect_rule_tests()
    if unstamped:
        print("Tests missing a timestamp suffix:", *unstamped, sep="\n  ")
        return 1
    INDEX_PATH.write_text(render_index(rules), encoding="utf-8", newline="\n")
    print(f"Wrote {INDEX_PATH.relative_to(PROJECT_ROOT)} ({len(rules)} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
